### ISSUE TITLE
Лишние переменные

### ISSUE THREAD

**Issue by casa7x** [TemaCap1992/JS_lesson_3#3]
https://github.com/TemaCap1992/JS_lesson_3/blob/9335cc1699a5ea97f4bc813394fb27607c3aa226/script.js#L73

Я думаю здесь нет смысла в этих промежуточных переменных, ты же сразу имеешь доступ в рамках итерации к объекту и его свойствам. И тебе здесь не надо хранить какое-то промежуточное состояние

**Comment by TemaCap1992** [comment]
fixed
